// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: new proj

#ifndef _NEW_PROJ_UI_H
#define _NEW_PROJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void logo_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
void ui_event_Arc4(lv_event_t * e);
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Label6;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_b;
extern lv_obj_t * ui_s;
extern lv_obj_t * ui_BT;
extern lv_obj_t * ui_Button5;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label9;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_pentagon_logo_png);    // assets\pentagon logo.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets\SETTINGS.png
LV_IMG_DECLARE(ui_img_battery_2_png);    // assets\battery 2.png

LV_FONT_DECLARE(ui_font_Font16);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
